### ISSUE TITLE
win7 64打开直接报错，管理权限+兼容模式都打不开。

### ISSUE THREAD

**Issue by yaheee** [BluePointLilac/ContextMenuManager#1]

**Comment by BluePointLilac** [comment]
你好，程序没有直接适配Win7，因为程序依赖.net framework 4.6，如需使用请安装.net 4.6以上版本
https://dotnet.microsoft.com/download/dotnet-framework/

**Comment by BluePointLilac** [comment]
你好，现在你可以下载2.0版本，已经适配了Win7
