### ISSUE TITLE
希望能关闭旧版WIN遗留的“从右到左的阅读顺序”等菜单

### ISSUE THREAD

**Issue by Makerabbit** [BluePointLilac/ContextMenuManager#107]
![图片](https://user-images.githubusercontent.com/37361918/140755276-cc475342-1dd0-48e3-91ad-55ae1674d9a4.png)

**Comment by BluePointLilac** [comment]
这些属于文本框的右键菜单没有提供定义接口，只支持文件系统的右键菜单哦
