### ISSUE TITLE
注册表编辑器未打开状态下无法自动跳转到注册表位置

### ISSUE THREAD

**Issue by timkayhou** [BluePointLilac/ContextMenuManager#108]
点击任意选择对象的齿轮图标→详细信息→注册表位置
此时新打开的注册表编辑器位置是上次的位置

**Comment by timkayhou** [comment]
另一台电脑没有此现象，应该不是软件问题。此issue关闭。

**Comment by BluePointLilac** [comment]
> 

不不不，这个问题确实存在，偶尔发生，代码逻辑没问题，但是不知道为什么定位消息没生效

**Comment by fireattack** [comment]
现在依然有这个问题
