### ISSUE TITLE
添加快捷键功能

### ISSUE THREAD

**Issue by MineFujiko** [BluePointLilac/ContextMenuManager#11]

**Comment by MineFujiko** [comment]
比如说：新建文件夹，邮件+W+F。那么，可以在程序中配置：新建Word也可以绑定一个按键。这个之前手动改动注册表是可以的。但是比较麻烦，能够集成到程序中，就再好不过了。：）

**Comment by BluePointLilac** [comment]
对项目修改名称，在名称里面加入后缀即可，比如“打开PS(&P)”，在系统中右键菜单显示效果就是"打开PS(P)"

**Comment by wordscode** [comment]
> 对项目修改名称，在名称里面加入后缀即可，比如“打开PS(&P)”，在系统中右键菜单显示效果就是"打开PS(P)"

键盘按p键，只会到那个列表项
还得点一下回车，才能打开？
