### ISSUE TITLE
Win11 新建菜单的问题

### ISSUE THREAD

**Issue by photkey** [BluePointLilac/ContextMenuManager#115]
![Snipaste_2022-01-24_13-15-39](https://user-images.githubusercontent.com/60434581/150725956-72677067-ae79-4fb8-bfe5-71d4e4269734.png)
如图所示：
`&TXT 文档` ContextMenuManager 中设置了，实际没有显示出来
右键 新建菜单中 `BMP 图像` `文本文档`  ContextMenuManager 中没有显示出来

**Comment by BluePointLilac** [comment]
这两个菜单在win11中内置了，跟注册表的无关了，无法处理
