### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by baldhead233** [BluePointLilac/ContextMenuManager#137]
# 我想在右键新建菜单那里添加一个Excel文件类型 就是xlsm 带有宏的工作簿 但是我尝试了各种方法 总是提示我excel不支持此文件类型 请检查扩展名什么的 我有创建个模板 模板正常打开 但是用右键新建的就是打不开 这是为什么?

**Comment by BluePointLilac** [comment]
在我的程序内右键你添加的那个.xlsm，详细信息，打开注册表，
![image](https://user-images.githubusercontent.com/55010935/183277685-85f2ab27-e140-45e9-833b-f59332ff2a88.png)
lei's类似这样，如果有Data键值和NullFile键值，就删除掉，然后新建一个FileName字符串键值，填入你的模板文件路径；或者如果你知道你的模板的二进制数据，可以填入Data键值里面。

**Comment by baldhead233** [comment]
![image](https://user-images.githubusercontent.com/93844898/183284240-2ffa43ad-cdb6-4686-9b86-a92f64742174.png)


> 在我的程序内右键你添加的那个.xlsm，详细信息，打开注册表， ![image](https://user-images.githubusercontent.com/55010935/183277685-85f2ab27-e140-45e9-833b-f59332ff2a88.png) 类似这样，如果有Data键值和NullFile键值，就删除掉，然后新建一个FileName字符串键值，填入你的模板文件路径；或者如果你知道你的模板的二进制数据，可以填入Data键值里面。

**Comment by BluePointLilac** [comment]
你要确定你的FileName键值是你的模板文件路径。模板没问题的话，那就不会有问题

**Comment by baldhead233** [comment]
确实是模板路径
C:\Program Files (x86)\Microsoft Office\root\vfs\Windows\SHELLNEW\EXCEL14M.XLSM

**Comment by baldhead233** [comment]
而且我模板可以打开 正常打开

> 你要确定你的FileName键值是你的模板文件路径。模板没问题的话，那就不会有问题

**Comment by BluePointLilac** [comment]
你给我看一下你的注册表截图，可以尝试在文件路径左右两侧加上英文双引号

**Comment by baldhead233** [comment]
试过了
可不可能excel某个设置才导致这样 
我网上各种方法都试了
![Uploading image.png…]()
这是在软件创建产生的文件夹:ShellNew

**Comment by baldhead233** [comment]
![image](https://user-images.githubusercontent.com/93844898/183289997-c9e7a804-9b26-415e-9b5c-f1721958da70.png)

**Comment by BluePointLilac** [comment]
加双引号也没用吗

**Comment by baldhead233** [comment]
没用

**Comment by baldhead233** [comment]
你试试你那边创建个xlsm试试 带宏工作簿

**Comment by BluePointLilac** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    那我就没办法了
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年8月7日 20:16
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [BluePointLilac/ContextMenuManager] 请教一下 (Issue #137)
        
      
    
  
  

没用

**Comment by baldhead233** [comment]
谢谢啦
