### ISSUE TITLE
请问 Windows 11 里，这种快捷方式怎么移除呢

### ISSUE THREAD

**Issue by tianyu94** [BluePointLilac/ContextMenuManager#138]
![image](https://user-images.githubusercontent.com/37231629/184464651-9535753b-4ac0-432d-aebb-45d646409ffd.png)

Windows 11 Pro 22000.856

**Comment by BluePointLilac** [comment]
你这应该是百度网盘加上去的，操作系统是英文的导致乱码了，你可以试试在百度网盘的设置里面取消勾选在我的电脑中显示百度网盘

**Comment by BluePointLilac** [comment]
我下载百度网盘看了一下，新增了个同步空间的功能，里面取消勾选显示虚拟盘符和桌面入口就可以了
