### ISSUE TITLE
程序字典支持软件内编辑

### ISSUE THREAD

**Issue by iloooo** [BluePointLilac/ContextMenuManager#14]
如题，我觉得为防止误操作可添加编辑按钮，点击后进行编辑和保存。最好防止文件编辑状态中继续使用软件，或者各种情况造成xml异常而导致Bug。
我发现软件也可以多开，好像都是别的是 ..\AppData\Roaming\ContextMenuManager\config?要不要进行多开限制啊？

顺便请问第三方规则大佬是如果获悉的？我发现我注册表中不一定有全部符合某个软件的命令，有可能被之前删过，后者说字典本来就是为了兼容各个版本情况。关于不同软件的字典，有没有思路或者教程，感谢~

**Comment by BluePointLilac** [comment]
我觉得没必要限制多开，因为我字典是在程序启动时就读取好了的，这里面编辑的字典只有重启软件后才会生效。第三方规则是我自己安装软件后监视注册表行为获取到的

**Comment by BluePointLilac** [comment]
实现部分，xml部分暂不打算实现
