### ISSUE TITLE
请教一下 误删注册表如何恢复

### ISSUE THREAD

**Issue by Yang-Kyle** [BluePointLilac/ContextMenuManager#141]
### 我应该是删了关联资源管理器的注册表
> 出现了诸如此类问题 我详细描述下 方便看出问题原因

- 无法在文件夹中打开
![00](https://user-images.githubusercontent.com/79508698/185575684-985a8d4b-8381-4166-8290-bee1123089e9.png)
- 无法跳转到文件路径
![000](https://user-images.githubusercontent.com/79508698/185576460-6828c727-4170-4f31-ad54-2d481b551f44.png)
- 其他软件调用或者系统程序中预览文件夹等一系列大部分操作也出错 （路径栏输入无法访问主机ftp 账户密码可以正常输入 说是连接不到IE浏览器 访问外设的ftp倒是没问题
![1111](https://user-images.githubusercontent.com/79508698/185585904-0f4c90f3-b354-46f9-a37c-279fbeb0f50b.png)
- 甚至文件夹与自己的关联也不行 每次双击进入一个文件夹都会弹出一个新的窗口
> 类似这种感觉

![000000](https://user-images.githubusercontent.com/79508698/185581498-c93d4ea4-ab06-456b-896a-e46702e2511e.png)
---
网上查了很多方法
比如：注册动态链接库文件 运行`regsvr32 "%SystemRoot%\System32\actxprxy.dll"`和`regsvr32 "%ProgramFiles%\Internet Explorer\ieproxy.dll"`
> 效果是这样子的

![123](https://user-images.githubusercontent.com/79508698/185583765-a12c18bc-5a17-439b-a773-d33d8ca3f862.png)
> 和这样子的

![324](https://user-images.githubusercontent.com/79508698/185583919-dc2a396c-c9c5-421c-9254-d94d11212adb.png)
也想到了导入注册表(谷歌的 我不会写) 居然说不是注册表文件 于是我又从一个问题跳到另一个问题不断地搜了很多问题
![12342](https://user-images.githubusercontent.com/79508698/185584539-b33142f6-f721-4cf6-b315-44dcd27861d1.jpg)

至此 我还是充满很多疑惑...
希望作者大佬能教教我咋恢复注册表备份

**Comment by BluePointLilac** [comment]
![image](https://user-images.githubusercontent.com/55010935/185654873-97a0b261-9813-4e87-8277-815050852d69.png)
你是不是把这个禁用了

**Comment by Yang-Kyle** [comment]
![00](https://user-images.githubusercontent.com/79508698/185771919-65b10dd4-084c-4c31-8633-9c9a9c9da70b.png)
谢谢回复 我检查了一下 开着呢

**Comment by Yang-Kyle** [comment]
喔 谢谢您！把这些在`新xx中打开`全选重启就好了 它居然自己把注册表给我生成辣 万岁 我的老伙计！

**Comment by luoluoluo22** [comment]
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/24725251/706f21a7-caf1-43de-a0e8-faeea3219afd)
我也遇到这个问题，但我没有这个选项怎么办
