### ISSUE TITLE
新建菜单缺少一个无后缀名文件的选项

### ISSUE THREAD

**Issue by lijian12345** [BluePointLilac/ContextMenuManager#143]
加了这个选项之后，可以方便添加一些冷门后缀名文件

**Comment by BluePointLilac** [comment]
这个想法挺好的，但是测试windows好像不支持新建无扩展名的，但你可以针对你想要的格式进行添加

**Comment by EricZhang233** [comment]
> 加了这个选项之后，可以方便添加一些冷门后缀名文件

新建txt，删后缀名就是你要的效果，其他后缀名新建会有占用，txt新建是最低占用的
