### ISSUE TITLE
请问锁定右键新建菜单能实现吗?

### ISSUE THREAD

**Issue by vvyoko** [BluePointLilac/ContextMenuManager#15]
有在用一个已经停止维护的类似工具。
里面有一个功能是锁定新建菜单。

我使用这个的逻辑是一般右键菜单一般在程序本身设置里能去除，而新建菜单反而是重灾区，程序自身反而没有相关的设置选项。

这样的话我只需要在系统装好的时候清理一下系统的右键，然后锁定新建菜单，后期再也不用打开这个软件了。
如果没有的话新安装一个程序假如污染了新建菜单就需要打开一次程序来处理。

附带一下程序，希望看看是否有实现的可能。

PS:运行前杀下毒检测下，这已经是2014年的软件了，来源也已经不清楚了。

[右键管家.zip](https://github.com/BluePointLilac/ContextMenuManager/files/5565093/default.zip)

**Comment by iloooo** [comment]
没考虑本软件实现，想到的办法是手动设置好想锁定的项，每次打开软件时对比锁定和现在的差异，提示下，后台程序把差异点恢复到锁定状态(关掉新增项，重新恢复删除关掉的项)

**Comment by BluePointLilac** [comment]
研究了一下，能够实现，不过我禁用的方法跟它不一样，达到的效果是一样的，只是不知道它是怎样实现的

**Comment by BluePointLilac** [comment]
找到了，禁用方法是一样的，差不多，都是操作注册表权限
