### ISSUE TITLE
界面拖动时出现拖延

### ISSUE THREAD

**Issue by SmileDream** [BluePointLilac/ContextMenuManager#16]
我的是144HZ屏幕，程序初次打开时拖动是正常，切换几个功能后拖动界面明显出现拖影的感觉，跟不上鼠标，不知道是什么问题

**Comment by BluePointLilac** [comment]
你好，这个问题我其实也知道，算一个Bug，但是我技术有限哈哈哈，不知道原因，也不知道怎么解决哈哈哈，可能涉及到内存处理方面吧。目前这个问题我无法修复，但对程序其他操作没有什么影响，希望你能先容忍一下

**Comment by BluePointLilac** [comment]
此问题已解决（大概，本机测试），问题大概出在窗体中控件太多上，之前是切换后没有立即清理而是先隐藏，先已修改为立即清理
