### ISSUE TITLE
添加对win11移除adobe的菜单支持

### ISSUE THREAD

**Issue by yige-yigeren** [BluePointLilac/ContextMenuManager#174]
如题，我找过了所有我知道的地方，但jpg文件的win11菜单依旧有转换为Adobe PDF

**Comment by QuantWorker** [comment]
> 如题，我找过了所有我知道的地方，但jpg文件的win11菜单依旧有转换为Adobe PDF

如果你使用的版本是 Adobe Acrobat Pro DC 2023
直接將以下文件夾任意改名或直接移除文件夾，即可停用Adobe PDF右鍵擴充
C:\Program Files\Adobe\Acrobat DC\Acrobat Elements

**Comment by yige-yigeren** [comment]
> > 如题，我找过了所有我知道的地方，但jpg文件的win11菜单依旧有转换为Adobe PDF
> 
> 如果你使用的版本是 Adobe Acrobat Pro DC 2023 直接將以下文件夾任意改名或直接移除文件夾，即可停用Adobe PDF右鍵擴充 C:\Program Files\Adobe\Acrobat DC\Acrobat Elements

谢谢啦

**Comment by QuantWorker** [comment]
> > > 如题，我找过了所有我知道的地方，但jpg文件的win11菜单依旧有转换为Adobe PDF
> > 
> > 
> > 如果你使用的版本是 Adobe Acrobat Pro DC 2023 直接將以下文件夾任意改名或直接移除文件夾，即可停用Adobe PDF右鍵擴充 C:\Program Files\Adobe\Acrobat DC\Acrobat Elements
> 
> 谢谢啦

我使用繁體中文版本，用此方式停用Adobe PDF右鍵擴充
發現滑鼠點擊工具列上方的文字選單(Menu)會有內部錯誤提示
例如點選檢視(View)裡頁面縮放會出現錯誤
但這些功能直接使用Adobe內建的工具按鈕，則正常使用。

**Comment by alanfox2000software** [comment]
HKEY_CLASSES_ROOT\PackagedCom\Package\AdobeAcrobatDCCoreApp_22.3.0.0_x64__pc75e8sa7ep4e, 找到 ContextMenuIExplorerCommandShim.dll 的2個GUID是
{A6595CD1-BF77-430A-A452-18696685F7C7}
{3282E233-C5D3-4533-9B25-44B8AAAFACFA}
另一個ContextMenuShim64.dll的GUID是
{30DEEDF6-63EA-4042-A7D8-0A9E1B17BB99}
把3個GUID封掉就可以

**Comment by bsszds** [comment]
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/d0086c4a-f55e-41dd-bc13-d548b17c7913)

**Comment by bsszds** [comment]
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/e1199b7e-f4db-45a3-b87f-b3075ce68a1a)

**Comment by bsszds** [comment]
卸载安装了好多次，终于找到原因了，在这里选择特定文件开启这个选项！！！！这下双击PDF文件就可以进入acrobat了
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/c4e0be99-1807-4c13-884b-9ffe181818e0)
