### ISSUE TITLE
请问如何单独隐藏回收站右键Everything 菜单？

### ISSUE THREAD

**Issue by YuI2333** [BluePointLilac/ContextMenuManager#182]
有没有办法不破坏其他文件夹Everything 菜单的情况下，单独隐藏回收站右键Everything 菜单？

**Comment by BluePointLilac** [comment]
定位到注册表位置，手动添加键值`AppliesTo`，值填写`System.ParsingName:<>"::{645FF040-5081-101B-9F08-00AA002F954E}"`
