### ISSUE TITLE
winrar可能有点问题

### ISSUE THREAD

**Issue by hankuksui** [BluePointLilac/ContextMenuManager#19]
![image](https://user-images.githubusercontent.com/11749191/103153847-93985080-47ce-11eb-9491-268ac677a891.png)
WinRAR中的压缩中的发送邮件已经禁用了，但是在文件的菜单上相关的菜单还是可以正常看到

**Comment by BluePointLilac** [comment]
你好，谢谢反馈，确实有这个问题，我可能之前收集字典时收集的是WinRAR旧版，现在测试新版发现注册表换了位置，也可能是我之前弄错了。请等待下版程序更新或字典更新，会修复这个问题。
