### ISSUE TITLE
关于Adobe Acrobat右键，找不到也删除不了

### ISSUE THREAD

**Issue by bsszds** [BluePointLilac/ContextMenuManager#191]
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/622109df-4a20-4ae3-a4e1-0564605a654b)

**Comment by bsszds** [comment]
用的是2023Acrobat
https://mp.weixin.qq.com/s/EJpNOCxY5iTpQTf2Kt57aA

卸载的时候查询到所在的注册表残留项
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/ec04d63f-6b03-4ea4-b8e7-6b710a42fd13)

**Comment by bsszds** [comment]
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/52306372/98942185-a1e1-41bd-89da-fab39b60378a)

**Comment by bsszds** [comment]
win 11 23H2系统

**Comment by bsszds** [comment]
https://github.com/BluePointLilac/ContextMenuManager/issues/174

**Comment by Jeasin** [comment]
参考这个帖子的评论：
> 对于Windows11：定位到 HKEY_CLASSES_ROOT\PackagedCom\Package\ 从左边找到AdobeAcrobatDCCoreApp 开头的项，然后删掉
[删除右键菜单中的“转换为Adobe PDF“](https://blog.csdn.net/ben_jobs/article/details/108636121)
