### ISSUE TITLE
关于转载您的原创程序的请求（已署名原创作者及出处）

### ISSUE THREAD

**Issue by toddliu1** [BluePointLilac/ContextMenuManager#2]
作者您好，我在处理迅雷右键菜单的时候无意间发现了您的原创程序，界面美观，功能强大，于是转载到了吾爱破解论坛（详见： Windows右键菜单管理程序ContextMenuManager v1.0.0.0 【开源软件】https://www.52pojie.cn/thread-1286028-1-1.html ) ，并在显著位置明确署名原创作者 @蓝点llilac 及出处Github项目主页，现请求您的转载授权，并反应一个众多网友提交的Bug：Windows 7 64位系统在安装了.Net framework 4.6以上版本的情况下，仍然会出现程序已停止，或者打开无反应的问题。

**Comment by BluePointLilac** [comment]
谢谢你的转载帮我传播这个软件，关于win7无法使用这个问题，我会抽时间尝试写一个适用于win7的版本出来
