### ISSUE TITLE
win10 20h2最新 新建菜单崩溃

### ISSUE THREAD

**Issue by dsyo2008** [BluePointLilac/ContextMenuManager#20]
ContextMenuManager 2.2会崩溃，2.0没问题。
![image](https://user-images.githubusercontent.com/3739056/103406005-171dbd00-4b94-11eb-9e7b-8419707aa9c9.png)
2.2
![image](https://user-images.githubusercontent.com/3739056/103406022-243aac00-4b94-11eb-98c5-43aed187ede6.png)
2.0

**Comment by Giter-t** [comment]
我也是，但是只是在更新了最新的releases以后

**Comment by BluePointLilac** [comment]
你好，方便加个QQ 1617859183远程看看吗

**Comment by BluePointLilac** [comment]
已解决
