### ISSUE TITLE
无法关闭搜狗输入法对pdf格式污染

### ISSUE THREAD

**Issue by huoxianribao** [BluePointLilac/ContextMenuManager#201]
软件只检测到了打印，但是关了这个没有效果。
火绒右键管理直接扫不到
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/72257969/6d3a9c52-595c-4dd1-9991-d48770410fe7)
![image](https://github.com/BluePointLilac/ContextMenuManager/assets/72257969/fc8f6246-6c14-4793-ab1a-3f8b90a03ddf)

**Comment by BluePointLilac** [comment]
在首页的文件里面找一下，这是直接关联到了所有文件的右键菜单里面了，你根据名字和文件位置自行判断一下是哪一项

**Comment by BluePointLilac** [comment]
在首页的文件里面找一下，这是直接关联到了所有文件的右键菜单里面了，你根据名字和文件位置自行判断一下是哪一项

**Comment by huoxianribao** [comment]
> 在首页的文件里面找一下，这是直接关联到了所有文件的右键菜单里面了，你根据名字和文件位置自行判断一下是哪一项

好吧，但是更简单的方式我还是通过搜狗里面的设置给关掉了
