### ISSUE TITLE
2.2.0.0 新建菜单 问题

### ISSUE THREAD

**Issue by ZevilL** [BluePointLilac/ContextMenuManager#21]
![image_11](https://user-images.githubusercontent.com/30890851/103413584-2d884080-4bb5-11eb-9a7e-b52d96af79cb.png)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ContextMenuManager.Controls.ShellNewList.LoadItems(List`1 extensions)
   在 ContextMenuManager.Controls.ShellNewList.LoadUnlockItems()
   在 ContextMenuManager.MainForm.SwitchGeneralItem()
   在 BulePointLilac.Controls.MySideBar.OnMouseDown(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

**Comment by BluePointLilac** [comment]
你好，方便加个QQ 1617859183远程看看吗

**Comment by ZevilL** [comment]
> 你好，方便加个QQ 1617859183远程看看吗

好的加你了

**Comment by ZevilL** [comment]
好的加你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BluePointLilac/ContextMenuManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月1日(星期五) 上午10:37
收件人:&nbsp;"BluePointLilac/ContextMenuManager"<ContextMenuManager@noreply.github.com&gt;;
抄送:&nbsp;"Lostself."<1216420934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BluePointLilac/ContextMenuManager] 2.2.0.0 新建菜单 问题 (#21)





 
你好，方便加个QQ 1617859183远程看看吗

**Comment by BluePointLilac** [comment]
已解决
