### ISSUE TITLE
能否支持移动右键菜单顺序？

### ISSUE THREAD

**Issue by staneee** [BluePointLilac/ContextMenuManager#22]
通过拖拽或者设置排序号来控制菜单顺序。

**Comment by BluePointLilac** [comment]
你好，右键菜单是复合的，融合了多个地方的注册表，这个无法进行排序的，[查看说明](https://t.bilibili.com/99316773?type=2)
系统仅支持像新建子菜单，二级子菜单这种限定在同一范围内的菜单排序
