### ISSUE TITLE
自定义灵活菜单位置

### ISSUE THREAD

**Issue by FroyoRab** [BluePointLilac/ContextMenuManager#23]
有一说一，
可以通过 对整个列表文件夹 添加**数字前缀**实现“自定义菜单灵活位置”的选项。
这样应该可以做到位置微调，比如上移一个，下移一个等。
对于产生的路径变动，可以在用户使用这个功能的时候进行警示。
另外，右键菜单里的这个分割线是取决于什么的啊，可以修改么

**Comment by BluePointLilac** [comment]
> 一级菜单的分割线我也不知道怎么添加，二级菜单可以添加分割线。

> 二级菜单也可以进行排序，但是一级菜单的位置调整功能我不太想做。

> 一是因为一级菜单是复合菜单，不仅仅是一个位置的注册表，[这里](https://t.bilibili.com/99316773?type=2)我解释过。

> 二是这样做会改动大量注册表名称，使原本的注册表面目全非却收效甚微，还得考虑其他注册表项对顺序的影响。

> 如果采用数字排序，当某一处注册表项内项目数超过10个数字排序就要考虑11和2的顺序了，当然换成字母排序会好一点的。

> 由于改注册表项目，假如有三项项名分别为 “DRC” “GDF” "XSW"，仅仅想让“XSW”位于“DRC” "GDF"中间，那该加什么前缀好一些呢？

> 而且某些第三方程序启动后会检查注册表项是否完整会重新写入，这样会导致注册表项重复。
