### ISSUE TITLE
第三方规则中的"任务栏 人脉、任务栏 Windows Ink 工作区"引起白屏

### ISSUE THREAD

**Issue by BahuangShanren** [BluePointLilac/ContextMenuManager#24]
使用这两个规则后，软件下方提示要重启资源管理器，点击重启后，资源管理器却未能重启成功，电脑白屏（但不是宕机的那种白屏，软件照样用）可能是资源管理器重启卡住引起的。

![0](https://user-images.githubusercontent.com/48022216/103868368-c6621300-5103-11eb-9f69-1b335055227e.png)

系统：Windows 10 19042.630

**Comment by BluePointLilac** [comment]
好的，谢谢反馈，如果一次重启不成功，你可尝试将打开或关闭的选项再操作一次，让这个重启资源管理器的框框出来后再重启一次试试

**Comment by BahuangShanren** [comment]
> 好的，谢谢反馈，如果一次重启不成功，你可尝试将打开或关闭的选项再操作一次，让这个重启资源管理器的框框出来后再重启一次试试

当然试过了，然而等了一会儿仍然没动静，没耐心继续等了，重启电脑后，这两个效果已成功应用，其他方面一切正常。

**Comment by BluePointLilac** [comment]
好的，谢谢，我尝试一下能不能优化这里的代码
