### ISSUE TITLE
有些文件类型的右键操作检测不到

### ISSUE THREAD

**Issue by qaqz111** [BluePointLilac/ContextMenuManager#25]
目前发现的有两种情况：
1. 右键操作记录在 HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExt\\.XXX 这个位置的操作检测不到
![无标题](https://user-images.githubusercontent.com/3367034/104137681-8f2c8400-53d9-11eb-8803-47dab7d5924d.png)

2. 直接记录在 HKCR\\.XXX\YYY 这个位置的操作检测不到
![无标题2](https://user-images.githubusercontent.com/3367034/104137692-99e71900-53d9-11eb-9b72-1e7f480127a4.png)

造成第一种情况的，我遇到的是极速迅雷1.X某个版本，进入迅雷关联bt文件后再取消，但是取消并没有什么卵用，双击种子文件还是开迅雷来下载。

造成第二种情况的，直接用这个软件随便做个什么扩展名的文件类型，加一个随便什么操作，这个操作会写入到某个位置（忘了是哪了，只记得是一个类似有 SystemAssociation 这两个单词的什么项下面），把 .XXX 直接剪切移动到 HKCR 下面，就会出现第二种情况。

**Comment by BluePointLilac** [comment]
你好能加QQ 1617859183远程看看吗

**Comment by qaqz111** [comment]
我机器上的注册表已经手动改了，现在没有这些情况了。

重现步骤已经写在上面了，你照那个试试能不能重现？
