### ISSUE TITLE
添加文件路径

### ISSUE THREAD

**Issue by panyuhang93** [BluePointLilac/ContextMenuManager#28]
能不能和右键管家一样添加文件路径呢,有时候只看名字不太确定是哪个菜单
![2021-01-30 16-19-33-32](https://user-images.githubusercontent.com/26140367/106351423-08ebc980-6317-11eb-98c0-dff5afdaa539.png)

**Comment by BluePointLilac** [comment]
可以实现这个需求，但是程序界面控件设计问题，改动一些地方可能导致整体不好看，所以我不打算加高项目宽度和更改。效果如图，问题就是有些许拥挤。将放在下次更新里面，在设置中开启，默认关闭。
![2021-2-1 14-58-19.png](https://i.loli.net/2021/02/01/sr6vE9qG4QxMmDK.png)

**Comment by panyuhang93** [comment]
谢谢你了！

**Comment by BluePointLilac** [comment]
考虑美观性，我决定将文件路径放在状态栏上，您觉得这样设计如何？
![2021-2-8 20-48-27.png](https://i.loli.net/2021/02/08/7ehqAyBcRQalr2N.png)

**Comment by panyuhang93** [comment]
大佬高兴加这个功能我就很开心了,这样挺不错的,比原来简洁
