### ISSUE TITLE
还剩下一个钉子户没找到。。。。

### ISSUE THREAD

**Issue by sky31even** [BluePointLilac/ContextMenuManager#29]
![image](https://user-images.githubusercontent.com/49628447/106543433-afff7980-6540-11eb-9a20-00b89af753b3.png)

![image](https://user-images.githubusercontent.com/49628447/106543492-cd344800-6540-11eb-873a-9a301828958a.png)

万兴PDF是在文件夹右键菜单里面出现的，但是在对应的未知没找到它

**Comment by BluePointLilac** [comment]
你看看在所有对象里面和目录里面有没有。文件夹的右键菜单包括 文件夹、目录 、 所有对象，以及类型文件夹（音频、视频、图片、文档）的右键菜单

**Comment by sky31even** [comment]
https://user-images.githubusercontent.com/49628447/106614394-41550700-65a6-11eb-8dfb-7e8d64dc42bf.mp4

都看了一遍还是没找着 = =

**Comment by BluePointLilac** [comment]
所有对象，这里也没有吗

**Comment by sky31even** [comment]
没有…

蓝点lilac <notifications@github.com>于2021年2月3日 周三14:50写道：

**Comment by Noah1995** [comment]
File Converter 不是吗

**Comment by sky31even** [comment]
不是……那是另一个软件

千千万万道不明 <notifications@github.com>于2021年2月3日 周三22:49写道：

**Comment by BluePointLilac** [comment]
我自己安装测试了一下，发现你的issues问题有误，这是出现在文件右键菜单上的，而不是文件夹上的，就是主页-文件的这个PEShellExtension，软件已添加字典，你将在日后的更新中看到万兴PDF专家而不是PEShellExtension.
![2021-2-4 10-12-26.png](https://i.loli.net/2021/02/04/hDO1JUW3IX69VvP.png)
![2021-2-4 10-13-5.png](https://i.loli.net/2021/02/04/D7eYCIv6NOKyzjc.png)

**Comment by sky31even** [comment]
感谢！！辛苦了
