### ISSUE TITLE
Windows 7 旗舰版 64位系统“已停止工作”错误

### ISSUE THREAD

**Issue by toddliu1** [BluePointLilac/ContextMenuManager#3]
Windows7 64位程序打开报错：“Windows右键管理 已停止工作” “出现了一个问题，导致程序停止工作。请关闭程序。”
详见下图：https://i.loli.net/2020/10/19/gjBWZMKhFNG4w7R.jpg

**Comment by BluePointLilac** [comment]
你好，目前暂不支持Win7，是我草率了，如果能够写出Win7版本的，我会推送更新的，每一个月检查一次更新

**Comment by BluePointLilac** [comment]
你好，现在适配了Win7系统，你可以下载2.0版本
