### ISSUE TITLE
右键拖拽菜单里的项目找不到

### ISSUE THREAD

**Issue by Mark-Imaginist** [BluePointLilac/ContextMenuManager#31]
![屏幕截图 2021-02-11 154124](https://user-images.githubusercontent.com/38615702/107611838-daa7ab80-6c7f-11eb-8e5b-ce2383146bcd.png)
如图，右键拖拽文件菜单里的项目好像管理不了

**Comment by BluePointLilac** [comment]
好的，将在新版中添加禁用拖拽菜单的功能
