### ISSUE TITLE
求助：如何编译使用该软件

### ISSUE THREAD

**Issue by boli-design** [BluePointLilac/ContextMenuManager#33]
github新人，按照网络教程clone了代码，安装git与npm，在文件夹根目录下输入npm install 以及 npm run dev 指令，均无法运行软件。如图：
![image](https://user-images.githubusercontent.com/57988442/108626944-d48aa980-748d-11eb-83ac-139458e28def.png)
求助：如何编译并运行软件，感谢指教！

**Comment by BluePointLilac** [comment]
我对git不了解，你没有IDE吗，可以用Visual Studio 2019进行编译啊
