### ISSUE TITLE
win10 2004启动失败

### ISSUE THREAD

**Issue by xja** [BluePointLilac/ContextMenuManager#34]
请问是哪里的问题，日志内容如下:

事件ID: 1000
错误应用程序名称: ContextMenuManager.NET.4.0.exe，版本: 3.0.0.0，时间戳: 0xe53b8454
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.572，时间戳: 0x1183946c
异常代码: 0xe0434352
错误偏移量: 0x0000000000023e49
错误进程 ID: 0x3798
错误应用程序启动时间: 0x01d709a05e7f0462
错误应用程序路径: C:\Users\Administrator\Downloads\ContextMenuManager.NET.4.0.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: db6ab85d-d75a-46db-af51-fae1202a57be
错误程序包全名: 
错误程序包相对应用程序 ID: 

事件ID: 1026
应用程序: ContextMenuManager.NET.4.0.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.FormatException
   在 System.Guid+GuidResult.SetFailure(ParseFailureKind, System.String, System.Object, System.String, System.Exception)
   在 System.Guid.TryParseGuidWithDashes(System.String, GuidResult ByRef)
   在 System.Guid.TryParseGuid(System.String, GuidStyles, GuidResult ByRef)
   在 System.Guid..ctor(System.String)
   在 BluePointLilac.Methods.GuidEx.TryParse(System.String, System.Guid ByRef)
   在 ContextMenuManager.Controls.ShellExItem.GetPathAndGuids(System.String, Boolean)
   在 ContextMenuManager.Controls.ShellList.LoadShellExItems(System.String)
   在 ContextMenuManager.Controls.ShellList.LoadItems()
   在 ContextMenuManager.MainForm.SwitchGeneralItem()
   在 ContextMenuManager.MainForm..ctor()
   在 ContextMenuManager.Program.Main(System.String[])

**Comment by BahuangShanren** [comment]
巧了么这不是，我一开始以为和这个有关👇

<img src="https://user-images.githubusercontent.com/48022216/108806677-50dfd280-75dd-11eb-9c5c-2ec16286f445.png" width="50%">

但解除锁定之后还是启动不了。
我又重新安装了 .NET SDK，也无法启动🤔

> Windows 10 专业版 20H2 19042.630

**Comment by BluePointLilac** [comment]
> 巧了么这不是，我一开始以为和这个有关👇
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/48022216/108806677-50dfd280-75dd-11eb-9c5c-2ec16286f445.png">
> 
> 但解除锁定之后还是启动不了。
> 我又重新安装了 .NET SDK，也无法启动🤔
> 
> > Windows 10 专业版 20H2 19042.630

你们好，我修复了一个已知bug，更新3.1版本，请查看是否能够正常启动。

**Comment by BluePointLilac** [comment]
你好，应该是在解析GUID时出错了，你应该用过火绒或者其他右键管理程序禁用过右键菜单，我之前优化了解析GUID的代码，却没想到带来了新的Bug，现在已经修复了。

**Comment by xja** [comment]
> 你好，应该是在解析GUID时出错了，你应该用过火绒或者其他右键管理程序禁用过右键菜单，我之前优化了解析GUID的代码，却没想到带来了新的Bug，现在已经修复了。

测试了新版确实能打开了，不知道 @BahuangShanren 那里有没有解决。不过有另外一个问题，我新开一个issue来说明吧

**Comment by BahuangShanren** [comment]
3.1版本可以正常启动使用🎉
