### ISSUE TITLE
windows terminal的右键菜单未列出

### ISSUE THREAD

**Issue by xja** [BluePointLilac/ContextMenuManager#36]
系统上安装了 [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)，在 目录背景 或 选中目录时，弹出右键会有 Open in Windows Terminal 的选项
![image](https://user-images.githubusercontent.com/9707809/108953502-43424f80-76a6-11eb-91f8-18fd1c14c4d4.png)

在翻遍所有程序内选项后并没有发现相关内容

**Comment by jasongzy** [comment]
这个与“使用 Skype 共享”类似，需要通过 GUID 锁来控制，GUID 是 `{9F156763-7844-4DC4-B2B1-901F640F5155}`

**Comment by xja** [comment]
> 这个与“使用 Skype 共享”类似，需要通过 GUID 锁来控制，GUID 是 `{9F156763-7844-4DC4-B2B1-901F640F5155}`

有详细的使用说明吗？添加到 GUID 锁 里面并没有什么反应。
![image](https://user-images.githubusercontent.com/9707809/108960622-29f2d080-76b1-11eb-8af4-6170f68c3124.png)

**Comment by BluePointLilac** [comment]
> > 这个与“使用 Skype 共享”类似，需要通过 GUID 锁来控制，GUID 是 `{9F156763-7844-4DC4-B2B1-901F640F5155}`
> 
> 有详细的使用说明吗？添加到 GUID 锁 里面并没有什么反应。
> ![image](https://user-images.githubusercontent.com/9707809/108960622-29f2d080-76b1-11eb-8af4-6170f68c3124.png)

按道理添加锁定项目后，会提示要重启一下资源管理器，你重启后看看

**Comment by xja** [comment]
> > > 这个与“使用 Skype 共享”类似，需要通过 GUID 锁来控制，GUID 是 `{9F156763-7844-4DC4-B2B1-901F640F5155}`
> > 
> > 
> > 有详细的使用说明吗？添加到 GUID 锁 里面并没有什么反应。
> > ![image](https://user-images.githubusercontent.com/9707809/108960622-29f2d080-76b1-11eb-8af4-6170f68c3124.png)
> 
> 按道理添加锁定项目后，会提示要重启一下资源管理器，你重启后看看

这就是重启资源管理器后截的图，好像是并没识别到？

**Comment by BluePointLilac** [comment]
安装 Terminal 后实测可以通过添加GUID锁禁用菜单
![2021-2-24 15-17-30](https://user-images.githubusercontent.com/55010935/108962310-8bb43a00-76b3-11eb-9b91-b14922c4515d.png)
![2021-2-24 15-18-12](https://user-images.githubusercontent.com/55010935/108962317-8ce56700-76b3-11eb-8a92-b5750bf116f9.png)
![2021-2-24 15-17-54](https://user-images.githubusercontent.com/55010935/108962323-8e169400-76b3-11eb-9e0b-eb2d4f587d02.png)

**Comment by jasongzy** [comment]
@BluePointLilac 建议把启用/禁用 Windows Terminal 菜单的选项加入主界面，方便直接操作

**Comment by xja** [comment]
> 安装 Terminal 后实测可以通过添加GUID锁禁用菜单
> ![2021-2-24 15-17-30](https://user-images.githubusercontent.com/55010935/108962310-8bb43a00-76b3-11eb-9b91-b14922c4515d.png)
> ![2021-2-24 15-18-12](https://user-images.githubusercontent.com/55010935/108962317-8ce56700-76b3-11eb-8a92-b5750bf116f9.png)
> ![2021-2-24 15-17-54](https://user-images.githubusercontent.com/55010935/108962323-8e169400-76b3-11eb-9e0b-eb2d4f587d02.png)

感谢，是我理解错了，原来是添加进去就可以了，不好意思。
另外这种 GUID 该如何查找呢？

**Comment by BluePointLilac** [comment]
> > 安装 Terminal 后实测可以通过添加GUID锁禁用菜单
> > ![2021-2-24 15-17-30](https://user-images.githubusercontent.com/55010935/108962310-8bb43a00-76b3-11eb-9b91-b14922c4515d.png)
> > ![2021-2-24 15-18-12](https://user-images.githubusercontent.com/55010935/108962317-8ce56700-76b3-11eb-8a92-b5750bf116f9.png)
> > ![2021-2-24 15-17-54](https://user-images.githubusercontent.com/55010935/108962323-8e169400-76b3-11eb-9e0b-eb2d4f587d02.png)
> 
> 感谢，是我理解错了，原来是添加进去就可以了，不好意思。
> 另外这种 GUID 该如何查找呢？

> @BluePointLilac 建议把启用/禁用 Windows Terminal 菜单的选项加入主界面，方便直接操作

一般来说，从xp系统以来，系统的右键菜单由3个部分构成：

1.自定义程度最高的Shell类型，可以改名称图标命令和添加注册表键值禁用等等；

2.封闭的ShellEx类型，这种甚至无法获取其名称和实际图标，也没有禁用启用的地方，我的程序能显示图标和名称其实是基于做了丰富的字典（这个耗费了我很多时间精力）。它只暴露一个GUID，我就是根据这个GUID做的字典，主界面禁用ShellEx项目的方法和网络上所有的右键管理程序一样通过删除备份注册表的方法来禁用它，不过我研究发现了系统提供了一个屏蔽GUID注册表的地方，所以在ShellEx类型的右键菜单上面有处理GUID-锁定GUID的功能，也可以在其他规则这里手动添加锁定；

3.系统级类型的，比如“复制”“删除”“排序方式”“粘贴快捷方式”，这种菜单不在注册表里面，而是封装在系统文件Shell32.dll里面（大概）。

但是最近Win10微软好像又在右键菜单里面添加了一个新的模块，它不符合以往的规则，专门提供给UWP应用的，它在这里
HKEY_CLASSES_ROOT\PackagedCom\Package\[UWP的包名称]\Classes\[右键菜单的GUID]，难得的是，我发现它的GUID也能被屏蔽锁定，可能是接入了ShellEx类型的接口吧。
本来我禁用“使用Skype共享“这个菜单专门写了部分代码，看来”Open with Windows Terminal“这个也一样了，但是感觉一直这样好蠢，因为可能以后会有更多的UWP应用使用了这个模块。我不知道现在有什么好方法使它通用下去。
