### ISSUE TITLE
支持便携化

### ISSUE THREAD

**Issue by Crystal-RainSlide** [BluePointLilac/ContextMenuManager#4]
支持将配置文件存储在本地。

目前最一般的实现方式是检测当前目录是否存在配置文件/配置文件夹，如果存在则为便携模式。

**Comment by BluePointLilac** [comment]
你好，此程序本身对配置文件的需求不是太大，在%AppData%\ContextMenuManager\config目录中存放的配置文件中config.ini只有两个用途，一是记录用户选择的语言字典文件路径，但是目前只有少部分国人在使用这个软件，只有中文甚至用不上这一条。另一个就是记录检测更新的时间，github的raw被墙，我就放在了gitee，但是gitee的raw有月访问上限就限制了一个月自动检测一次更新。
该目录下其他文件也是在程序每月检测时，从gitee上下载字典文件进行补充。不放在程序同目录是为了看起来像一个单文件程序，这样exe文件到处放置都不用再写一份配置文件占用地方，也看起来更加绿色。当然用户也可以在程序的"关于"----"程序字典"里面右键保存字典文件，进行自定义添加字典条目，为了与网络下载文件进行区分就存在程序同目录，但是大部分用户用不上这个，这个功能就做的不是很明显。
