### ISSUE TITLE
BUG：只对管理员账户有作用，对标准账户作用有限

### ISSUE THREAD

**Issue by gordonwalkedby** [BluePointLilac/ContextMenuManager#40]
我平时只使用Windows标准账户，我在标准账户下的右键菜单无法很好地被 CMM 管理。  
比如下面图片中的 Git Bash 和 VScode ，就是只安装在我的标准账户之下的。  
环境： Windows 10 x64
软件版本：  3.1.0.0

![图片1](https://s3.ax1x.com/2021/03/06/6n2ER0.png)

**Comment by BluePointLilac** [comment]
这几个选项在目录背景里面，应该和账户没关系

**Comment by gordonwalkedby** [comment]
我这边反复看了半天，也没找到管理这个 Git 的。    
这个 Git 安装在 `C:\Users\u2\AppData\Local\Programs\Git`     u2 是我的标准账户   
再比如，那个 PowerShell 就是安装到管理员账户的，所以就有。

**Comment by BluePointLilac** [comment]
你能发一下你的软件目录背景这一项的截图吗

**Comment by gordonwalkedby** [comment]
截图：   
![图片1](https://s3.ax1x.com/2021/03/06/6n5BFg.png)   

![图片2](https://s3.ax1x.com/2021/03/06/6n5ySs.png)

**Comment by BluePointLilac** [comment]
可以加个QQ 1617859183远程看看吗

**Comment by gordonwalkedby** [comment]
我是戈登登，加你了（

**Comment by BluePointLilac** [comment]
恕本人暂无能力和时间兼容多账户问题，此issues暂时关闭
