### ISSUE TITLE
这是功能重复吗？

### ISSUE THREAD

**Issue by AmenLemon** [BluePointLilac/ContextMenuManager#42]
![QQ截图20210308044901](https://user-images.githubusercontent.com/5909257/110254308-9f23a700-7fc9-11eb-9b57-862bed914857.png)
请问这两个重启资源管理器效果一样吗？

**Comment by BluePointLilac** [comment]
效果一样，但是原理不一样，第一个可用就用第一个最好，第二个是给不能用第一个的系统用的
