### ISSUE TITLE
"你的系统版本太低，不支持隐藏子菜单"

### ISSUE THREAD

**Issue by Harriser** [BluePointLilac/ContextMenuManager#44]
- 环境： Windows 7 sp1 x64
- 软件：ContextMenuManager.NET 4.0
- 版本： 3.1.0.0

#### 问题描述：

1. 操作部分选择出现提示，"你的系统版本太低，不支持隐藏子菜单"，实际在操作完成后是可以正常“显示”或"隐藏"。

![ContextMenuManager NET_4 0_210308_1615208776V](https://user-images.githubusercontent.com/13331604/110325844-d12d1b80-8052-11eb-9f36-55ebff7cd8b7.jpg)

2. 部分菜单下，滑动鼠标滚轮，会出现弹窗"程序将会被重新启动!"

![ContextMenuManager NET_4 0_210308_1615209402w](https://user-images.githubusercontent.com/13331604/110326839-27e72500-8054-11eb-895f-535217c10a51.jpg)

3. Releases中"3.1.1.0"，文件版本显示为"3.1.0.0"，导致程序经常性弹出更新提示。

**Comment by BluePointLilac** [comment]
您好，请问新版本有这些问题吗

**Comment by Harriser** [comment]
> 您好，请问新版本有这些问题吗

没有这些问题了，感谢您做出这么方便的工具

**Comment by BluePointLilac** [comment]
好的，也谢谢您的反馈！
