### ISSUE TITLE
Win10的MD杀毒老是复发

### ISSUE THREAD

**Issue by PuppetVaysa** [BluePointLilac/ContextMenuManager#45]
禁用之后，一重启系统又会自动开启。文件、目录、磁盘分区 里的都这样

![无标题](https://user-images.githubusercontent.com/8633108/111089526-4626b680-8567-11eb-8774-b2bc0bebbc5c.png)

**Comment by BluePointLilac** [comment]
右键该项目，处理GUID，锁定GUID，即可永久禁用
