### ISSUE TITLE
希望能够禁用 Windows Terminal 的右键菜单

### ISSUE THREAD

**Issue by vvyoko** [BluePointLilac/ContextMenuManager#46]
如链接：
https://www.cnblogs.com/TianFang/p/13843696.html

**Comment by BluePointLilac** [comment]
程序可以的呀，也是用的这种方法
![Uploading 2021-3-16 19-48-55.png…]()

**Comment by BluePointLilac** [comment]
程序可以的呀，也是用的这种方法
![Uploading 2021-3-16 19-48-55.png…]()

**Comment by BluePointLilac** [comment]
![2021-3-16 19-48-55](https://user-images.githubusercontent.com/55010935/111304701-00660d00-8691-11eb-9959-335dd6337445.png)
