### ISSUE TITLE
Not implemented 错误

### ISSUE THREAD

**Issue by bcaso** [BluePointLilac/ContextMenuManager#47]
![image](https://user-images.githubusercontent.com/32212684/112630132-25683600-8e70-11eb-9b8a-1984f15a8518.png)
小白，不知道动了哪一项，然后win + r 运行：control 时，无法打开 控制面板。
类似的还有：win + break 键查看系统信息
![image](https://user-images.githubusercontent.com/32212684/112630390-7e37ce80-8e70-11eb-9286-deed209e7733.png)

**Comment by BluePointLilac** [comment]
能加个QQ 1617859183远程看看吗
