### ISSUE TITLE
在程序中添加一个按钮，视觉上隐藏已关闭的“菜单项目”

### ISSUE THREAD

**Issue by renmu123** [BluePointLilac/ContextMenuManager#48]
有时候菜单项会比较多，但是有时候又只想对“未关闭项”进行编辑，现在的样式用起来就比较累

![image](https://user-images.githubusercontent.com/26896790/113644830-360e7c80-96b8-11eb-8f69-6b87cec385f2.png)
示例

**Comment by BluePointLilac** [comment]
好的，将在新版本中设置中添加该选项
