### ISSUE TITLE
How to cancel AMD Radeon Software on win10 desktop?

### ISSUE THREAD

**Issue by Yikng** [BluePointLilac/ContextMenuManager#51]
How to cancel AMD Radeon Software on win10 desktop?
There is no such service to choose from in the desktop background, and no other categories.

**Comment by BluePointLilac** [comment]
![image](https://user-images.githubusercontent.com/55010935/115220610-566c1b80-a13b-11eb-9d09-bd3cca01ece9.png)
It could be in the background here
