### ISSUE TITLE
Skype共享问题

### ISSUE THREAD

**Issue by LevenTark** [BluePointLilac/ContextMenuManager#54]
右键中使用Skype共享选项没有被扫描到 是因为它的注册表原因么 希望大佬解决一下 谢谢
![微信图片_20210423014900](https://user-images.githubusercontent.com/55422498/115763382-001b0900-a3d7-11eb-8c76-dc6010be0cb8.png)
![微信图片_20210423014728](https://user-images.githubusercontent.com/55422498/115763400-027d6300-a3d7-11eb-904b-4fa794b67613.png)

**Comment by BluePointLilac** [comment]
在主页-文件最下面应该有吧
![image](https://user-images.githubusercontent.com/55010935/115952375-19779e80-a518-11eb-84e0-d29612cbf2d3.png)
