### ISSUE TITLE
有些软件在每次更新后，右键会重新开启。

### ISSUE THREAD

**Issue by houinchengdu** [BluePointLilac/ContextMenuManager#55]
有些软件在每次更新后（比如115浏览器、迅雷、QQ音乐等），已经关闭的右键就会重新开启。能不能增加个搜索功能，一次搜索某个软件的所有右键；或者关闭后就永久关闭，即使软件更新后也不会重新开启。

**Comment by BluePointLilac** [comment]
可以尝试右键对应项目，处理GUID，锁定GUID，重启explorer即可。
搜索功能是做不到的，因为一个程序可以注册多个GUID，无法做出包含所有程序的字典，右键菜单注册表相关项目也是到处都有，无法进行搜索
![image](https://user-images.githubusercontent.com/55010935/115990519-4306f780-a5f6-11eb-9c61-caf21d5ad1bb.png)
