### ISSUE TITLE
希望对 exe 等可执行文件，加入禁止访问网络的右键菜单

### ISSUE THREAD

**Issue by sanmaodo** [BluePointLilac/ContextMenuManager#57]
这个功能很实用，对一些不太放心的程序，禁用网络可以保障安全，希望 ContextMenuManager 能添加，谢谢！

**Comment by wxlg1117** [comment]
你这玩笑开的有点大...人家只是一个系统注册表修改工具...你应该整的是防火墙..

**Comment by sanmaodo** [comment]
以前用过一种右键菜单增强工具，它可以做到，不清楚它的运行机制
<img width="270" alt="0506184339" src="https://user-images.githubusercontent.com/29154707/117286445-bca1af80-ae58-11eb-84c8-84572535b6e7.png">

**Comment by BluePointLilac** [comment]
## 研究了一下命令行添加删除防火墙规则，实现起来很简单

### 方法一：按图自行添加命令
#### 步骤一：创建一级菜单
![2021-5-6 20-23-16](https://user-images.githubusercontent.com/55010935/117298163-a07a2e80-aea9-11eb-97e4-57bd304f59be.png)
![2021-5-6 20-23-48](https://user-images.githubusercontent.com/55010935/117298188-a8d26980-aea9-11eb-9861-e14602104d3e.png)

#### 步骤二：创建二级菜单
![2021-5-6 20-24-12](https://user-images.githubusercontent.com/55010935/117298304-cb648280-aea9-11eb-95ba-2e693b18367b.png)

> 如下图分别创建四个子菜单项目
![2021-5-6 20-26-33](https://user-images.githubusercontent.com/55010935/117298460-f7800380-aea9-11eb-8ae4-14d6e1f44092.png)

> 菜单命令都是**_netsh_**
> 命令参数分别为：
1. 禁止入站：**_advfirewall firewall add rule name="%1" dir=in program="%1" action=block_**
2. 禁止出站：**_advfirewall firewall add rule name="%1" dir=out program="%1" action=block_**
3. 允许入站：**_advfirewall firewall delete rule name="%1" dir=in  program="%1"_**
4. 允许出站：**_advfirewall firewall delete rule name="%1" dir=out  program="%1"_**

> 记得都需要勾选**_ShellExecute_**
- Verb选ruans（以管理员身份运行命令）
- WindowStyle调整为0（隐藏命令黑窗口）

#### 步骤三：修改图标（看自己需要）
![QQ截图20210506204118](https://user-images.githubusercontent.com/55010935/117299789-80e40580-aeab-11eb-8a78-c6355352dddf.png)
![2021-5-6 20-41-40](https://user-images.githubusercontent.com/55010935/117299807-82adc900-aeab-11eb-8cca-02b10121bf42.png)
右键添加图标或更改图标
- 一级菜单选FirewallControlPanel.dll里面的
- 二级菜单选imageres.dll里面的

### 方法二：直接导入我的注册表文件
[防火墙规则.zip](https://github.com/BluePointLilac/ContextMenuManager/files/6436327/default.zip)

### 方法三：通过增强菜单字典添加
等待后续程序网络字典自动更新
在增强菜单里面启用
![2021-5-7 0-52-3](https://user-images.githubusercontent.com/55010935/117336147-75560600-aece-11eb-8302-b5be18d7eb3c.png)

**Comment by BluePointLilac** [comment]
### 方法二：直接导入我的注册表文件
[防火墙规则.zip](https://github.com/BluePointLilac/ContextMenuManager/files/6436327/default.zip)

### 方法三：通过增强菜单字典添加
等待后续程序网络字典自动更新
在增强菜单里面启用
![2021-5-7 0-52-3](https://user-images.githubusercontent.com/55010935/117336147-75560600-aece-11eb-8302-b5be18d7eb3c.png)

**Comment by BluePointLilac** [comment]
### 实现效果如图
![QQ截图20210507010032](https://user-images.githubusercontent.com/55010935/117337201-ac78e700-aecf-11eb-8e13-f50a39bbc58a.png)

**Comment by sanmaodo** [comment]
@BluePointLilac 非常感谢！
