### ISSUE TITLE
最新版打不开了。

### ISSUE THREAD

**Issue by corgile** [BluePointLilac/ContextMenuManager#60]
两个.NET版本的exe都试过了，双击程序，当前资源管理器窗口卡死（其他窗口没事）。只能重启资源管理器以关闭。
Windows信息：
![image](https://user-images.githubusercontent.com/48396880/118358797-1ae63500-b5b3-11eb-825e-de60753d48ad.png)

**Comment by BluePointLilac** [comment]
能加QQ1617859183远程看看吗

**Comment by BluePointLilac** [comment]
经远程测试应该是预览版系统问题

**Comment by aboutZZ** [comment]
+1 我是正式版Win10 21H1
双击运行鼠标一直转圈，资源管理器卡死。
@BluePointLilac

**Comment by aboutZZ** [comment]
等了半天，弹出来个`Smart Screen` 筛查弹窗。原来`Smart Screen` 一直在联网检查这个程序，结果网络超时连不上。
wdnmd辣鸡Win10。关闭Win10 `Smart Screen` 功能即可，顺便把Defender实时防护也给弄了。
