### ISSUE TITLE
Windows Defender报毒

### ISSUE THREAD

**Issue by Kagami-sama** [BluePointLilac/ContextMenuManager#61]
很方便的工具，但Github下载的zip，解压报毒（如下图）：

<img src="https://user-images.githubusercontent.com/15805746/118607403-1d32d400-b7eb-11eb-9917-fed5c9d2e251.png" width="350">

直接下载exe有同样的问题，不确定是不是误报。
如果是的话是否可以考虑解决一下，总觉得有点别扭。。。

**Comment by BluePointLilac** [comment]
这个无法解决，程序操作注册表和文件，需要敏感权限，被误报率高得离谱的Windows defender报毒很正常，程序代码开源，每个人可进行编译检查，是没任何问题的，能解决的方法只有一个，花钱购买签名证书，但是那玩意很贵。只能委屈你加一下WD白名单，或者使用火绒等第三方杀软了

**Comment by kaichundaily** [comment]
这个还会被腾讯ACE扫到，扫到的话就会被强制退出游戏
