### ISSUE TITLE
[BUG]反馈右键哈希值的bug

### ISSUE THREAD

**Issue by DiexMi** [BluePointLilac/ContextMenuManager#63]
功能位置：其他规则-文件-获取哈希值
问题描述：文件名带有任意标点符号及空格时，获取哈希值功能的powershell会报错
错误描述：

    Get-FileHash : 找不到接受实际参数“-”的位置形式参数。
    所在位置 行:1 字符: 1
    + get-filehash -literalpath D:\新建文本文档 - 副本.flac -algorithm SHA1 | forma ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Get-FileHash]，ParameterBindingException
        + FullyQualifiedErrorId : PositionalParameterNotFound,Get-FileHash

**Comment by BluePointLilac** [comment]
谢谢反馈，你可以右键项目，详细信息，更改命令，将所有"%1"替换为\""%1"\"，如下：
```
powershell -noexit get-filehash -literalpath \""%1"\" -algorithm SHA1 | format-list;get-filehash -literalpath \""%1"\" -algorithm SHA256 | format-list;get-filehash -literalpath \""%1"\" -algorithm SHA384 | format-list;get-filehash -literalpath \""%1"\" -algorithm SHA512 | format-list;get-filehash -literalpath \""%1"\" -algorithm MACTripleDES | format-list;get-filehash -literalpath \""%1"\" -algorithm MD5 | format-list;get-filehash -literalpath \""%1"\" -algorithm RIPEMD160 | format-list
```

**Comment by BluePointLilac** [comment]
此命令收集自网络，我自己了解了下Powershell语法，现优化如下：
```
powershell -NoExit Write-Host '"%1"';$args = 'MD5', 'SHA1', 'SHA256', 'SHA384', 'SHA512', 'MACTripleDES', 'RIPEMD160'; foreach($arg in $args){Get-FileHash '"%1"' -Algorithm $arg | Select-Object Algorithm, Hash | Format-Table -Wrap}
```

**Comment by ssssssbbb** [comment]
> 此命令收集自网络，我自己了解了下Powershell语法，现优化如下：
> 
> ```
> powershell -NoExit Write-Host '"%1"';$args = 'MD5', 'SHA1', 'SHA256', 'SHA384', 'SHA512', 'MACTripleDES', 'RIPEMD160'; foreach($arg in $args){Get-FileHash '"%1"' -Algorithm $arg | Select-Object Algorithm, Hash | Format-Table -Wrap}
> ```

经测试这个不起作用，像打了一行空命令一样无任何返回，上面那个反倒可以，但是结果太占篇幅

**Comment by ssssssbbb** [comment]
> Get-FileHash

Get-FileHash 后面加入-literalpath就可以了
