### ISSUE TITLE
建议支持powershell

### ISSUE THREAD

**Issue by eritpchy** [BluePointLilac/ContextMenuManager#64]
实测可以用 且表现良好
![image](https://user-images.githubusercontent.com/8630635/120915954-4901f500-c6d9-11eb-8e28-24ff9e3157b2.png)
![image](https://user-images.githubusercontent.com/8630635/120915988-6931b400-c6d9-11eb-9473-008b1c2b41af.png)
![image](https://user-images.githubusercontent.com/8630635/120916004-79e22a00-c6d9-11eb-9d91-0f505f388e89.png)

**Comment by BluePointLilac** [comment]
后续更新将支持所有类型文件
