### ISSUE TITLE
建议一级菜单项目支持使用公共引用

### ISSUE THREAD

**Issue by eritpchy** [BluePointLilac/ContextMenuManager#65]
公共引用好像只能作为多级菜单项目插入, 那么一级菜单项目怎么办?
![image](https://user-images.githubusercontent.com/8630635/120916134-5e2b5380-c6da-11eb-872e-f996d426e7ee.png)

**Comment by BluePointLilac** [comment]
可以，但那将不叫引用，而是复制了
