### ISSUE TITLE
文件夹和目录有什么区别啊？

### ISSUE THREAD

**Issue by hankuksui** [BluePointLilac/ContextMenuManager#70]
文件夹和目录有什么区别啊？不是很明白这个

**Comment by BluePointLilac** [comment]
文件夹只针对文件夹本身，目录既针对文件夹也针对文件夹里面的所有文件和文件夹。这是逻辑上的问题，右键菜单运行的命令处理对象的区别。当然视觉上都会出现在文件夹的右键菜单上
