### ISSUE TITLE
这病毒是报错的是吗？

### ISSUE THREAD

**Issue by zhenjie1999** [BluePointLilac/ContextMenuManager#71]
![image](https://user-images.githubusercontent.com/75268245/121987194-f4463480-cdd2-11eb-8307-96f69070c931.png)
![image](https://user-images.githubusercontent.com/75268245/121987203-fc9e6f80-cdd2-11eb-89cf-e7ee31d66975.png)

**Comment by BluePointLilac** [comment]
软件有很多敏感行为，读写修改注册表内容和权限，读写文件，访问网络，杀软很容易误报，请自行添加白名单。
