### ISSUE TITLE
[Feature Request] 增加“复制路径”的选项

### ISSUE THREAD

**Issue by northword** [BluePointLilac/ContextMenuManager#72]
下图是个我以前用过的一个右键菜单管理的小程序，他这个有个“增加菜单”的选项卡里预设了一些菜单，“复制路径”我觉得还是蛮有用的，~~不过这个程序添加的菜单必须依赖于这个程序，当程序变了位置后，添加的菜单就不能用了（好像是）~~，咱们能不能也添加这个功能？
或者说已有的已经可以实现，如果这样的话，还请麻烦告诉我一下方法，感谢！

![Snipaste_2021-06-17_22-18-14](https://user-images.githubusercontent.com/44738481/122414782-fa4a3a00-cfb9-11eb-9167-f87cb4058b0f.png)

**Comment by BluePointLilac** [comment]
在程序的“其他规则”—“增强菜单”—“程序字典”—“所有对象”这里有你想要的，增强菜单里面有很多很好用的命令你可以看一下，并且程序的字典是可以不断扩充的，如果你有比较好的命令也可以贡献到此项目
