### ISSUE TITLE
一些Bug

### ISSUE THREAD

**Issue by zxcyyyyy000** [BluePointLilac/ContextMenuManager#74]
在点击<主页> -> <发送到>的选项的时候，会出现未经处理的异常。一些异常信息如下

************** 异常文本 **************
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ContextMenuManager.Controls.SendToItem.get_IconLocation()
   在 ContextMenuManager.Controls.SendToItem.get_ItemIcon()
   在 ContextMenuManager.Controls.SendToItem.set_FilePath(String value)
   在 ContextMenuManager.Controls.SendToList.LoadItems()
   在 ContextMenuManager.MainForm.SwitchGeneralItem()
   在 BluePointLilac.Controls.MySideBar.OnMouseDown(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

除此之外，右键点击诸如zip等的压缩文件，不会出现未被关闭的选项（如7-zip的解压选项），并且右键文件后的“发送到”选项卡也会变成空白。经验证在Ver 3.3.2.0版本与.1版本该bug都存在

**Comment by BluePointLilac** [comment]
可以加个QQ 1617859183远程看看吗

**Comment by zxcyyyyy000** [comment]
好的
