### ISSUE TITLE
有个good idea

### ISSUE THREAD

**Issue by dnknn** [BluePointLilac/ContextMenuManager#75]
<details><summary> Ø<s>过时</s>Ø </summary>

```js

```
因为看到支持自定义添加右键菜单项, 
那么 能否顺便支持1个功能: 自定义右键的 `(&🔠)` (似乎叫做助记键)

> 如 右键后 ⥅ 再按 `R` 会弹出 属性弹框, 这个 `R` 就是右键助记键

- 它的实现原理很简单, 即纯文本实现的 :
	* 如右键的名称字符串是 `属性` 
	* 然后字符串变为 `属性(&R)` 那么就实现了.

> 这个原理是任何地方都通用的.

---------------------------------------------------------------------
　　　

最后, 只不过在 ContextMenuManager 程序上, 不知是否能实现, 

另外, 假如能实现的话, 也要考虑 有的右键菜单的字符串是根据 `变量` 动态生成的.

> 如果不易实现, 请直接关闭!

</details>

**Comment by dnknn** [comment]
更改文本 就能实现了, 因此关闭issue!

**Comment by dnknn** [comment]
不过有个 显示 Bug (实际上是能输入和更改, 仅仅是显示问题而已)
估计是改动了系统字号有关 https://github.com/Tatsu-syo/noMeiryoUI/releases

![image](https://user-images.githubusercontent.com/10995302/127752263-875275f0-c56b-454e-83e4-d7c3b4b0dc15.png)

**Comment by BluePointLilac** [comment]
快捷键我一直知道，但是跟你说的一样，纯文本形式的，跟显示文本绑定在一起了，直接改显示文本即可，这个是留给自己懂的人去发现的。实际上连括号都不需要，最重要的就是那个`&`符号，除了接字母也可以接数字。在编程里面按钮文本都可以这样设置。

至于这个显示问题，是第一次见，应该就是你改了字号的问题。我有空再看看，我的控件布局都是直接用代码写的，没有用VS图形化界面拖控件，可能哪里没考虑字号吧。

这个程序里面有很多细节功能不好直接展现，不然程序设计上就会很臃肿，比如这里还有一个使用ShellExecute函数包装命令的，通过这个函数包装，可以以管理员身份运行命令，可以隐藏窗口执行命令。
![2021-8-1 12-39-6](https://user-images.githubusercontent.com/55010935/127759495-9769ed68-7116-4a82-8349-8c78f481528c.png)

现在没时间写一个文档，不然可以好好介绍一下这个程序。

**Comment by dnknn** [comment]
感谢答复,  之前网络上有很多人想要恢复 回收站图标 右键的 B 按键, 
很多人是通过改注册表实现的.
想不到 你这个软件工具, 竟然能轻松一键实现.

- 显示的Bug , 你可以用这个软件去测试 https://github.com/Tatsu-syo/noMeiryoUI/releases
这是唯一能改动系统字号的工具了, 由于系统字号默认一般就 `9px` 左右, 太小了, 
有很多人会稍微改大一点.

- 系统DPI是这样的 [image](https://user-images.githubusercontent.com/10995302/127777096-51d60acb-329b-4946-868e-f5ebceef8323.png)
	提示: 浏览器地址栏打开 `ms-settings:easeofaccess-display` 或用按键按 `WinU`



---------------------------------------------------------------------
　　　

ShellExecute

**Comment by dnknn** [comment]
感谢答复,  之前网络上有很多人想要恢复 回收站图标 右键的 B 按键, 很多人是通过改注册表实现的.
想不到 你这个软件工具, 竟然能轻松一键实现.

- 显示的Bug , 你可以用这个软件去测试 https://github.com/Tatsu-syo/noMeiryoUI/releases
这是唯一能改动系统字号的工具了, 由于系统字号默认一般就 `9px` 左右, 太小了, 
有很多人会稍微改大一点.

- 系统DPI是这样的 [image](https://user-images.githubusercontent.com/10995302/127777096-51d60acb-329b-4946-868e-f5ebceef8323.png)
	提示: 浏览器地址栏打开 `ms-settings:easeofaccess-display` 或用按键按 `WinU`



---------------------------------------------------------------------
　　　

- 确实需要 📖Documentation 文档帮助
	如什么 `ShellExecute` 这些都搞不懂, 还有各个术语的含义, 
	如果可以, 最好是图解说明, 一图胜过千万语. 
	例如这个术语是指向哪个地方, 一个截图就说明一切了

- 都弄懂了后, 那这个工具就不仅是右键管家婆那么简单了, 
	更可以作为 `快捷启动` 的好帮手! 如 增删减 右键菜单项
	尤其可以 自定义自由新增 右键菜单项, 那么就有无穷可能性了.
	我就给 `WinX` 增加了几个常用的快捷方式, 感觉还不错!

**Comment by dnknn** [comment]
@BluePointLilac 请教1个问题,

如何为 `.exe` 类型, 添加 Bandizip解压缩, 因为很多exe具有双重性质, 可以解压变为绿色版.

这是bandizip的命令行参数 https://www.bandisoft.com/bandizip/help/parameter/

- 似乎 `-target:auto` 就是自动解压的参数, 但结果是无效的
![image](https://user-images.githubusercontent.com/10995302/127833220-96b0f0aa-51eb-4efd-b43f-358fd088dd52.png)


---------------------------------------------------------------------
　　　
- 此外 适当在必要的地方, 加个`tooltip` 
	类似于html的 ` .title = "tooltip" ` (鼠标悬停着会有tooltip帮助信息可看)



---------------------------------------------------------------------
　　　

- 另外, URL打不开, 是个Bug [image](https://user-images.githubusercontent.com/10995302/127832685-38d79a68-1bc7-4c7d-92d9-54acbd50bc8a.png)

**Comment by BluePointLilac** [comment]
- 字号显示问题已经解决，程序很多地方使用系统默认字体进行设计，未考虑用户可能变更字号大小，现已经添加字号限制。

- 添加命令参数，针对文件(夹)需要添加 `%1`，针对目录需要添加 `%v`，代表文件(夹)或目录对象的路径，程序会默认给你添加的。结合文档应该这样写
![2021-8-2 17-48-3](https://user-images.githubusercontent.com/55010935/127842085-673506d7-f582-422c-bcc3-abfab3da9396.png)

但是程序考虑到文件路径可能带空格的问题，会给命令的文件路径和参数都添加双引号，故这里有重复，你需要右键 `详细信息`-- `更改命令`，删掉多余的两个引号。
![2021-8-2 17-49-34](https://user-images.githubusercontent.com/55010935/127842634-806969d7-c128-4e5c-866e-9c6aad9cd425.png)

- 至于URL这个我自己这边是没有问题的，我这边直接调用的 `explorer.exe "url"`，
![2021-8-2 17-55-38](https://user-images.githubusercontent.com/55010935/127842989-0225de88-c39c-4e6f-9e6a-85b068100000.png)

**Comment by BluePointLilac** [comment]
然后可以加个QQ `1617859183`，可以更方便的联系。
