### ISSUE TITLE
Unhandled exceptions - "其他规则"

### ISSUE THREAD

**Issue by delgh1** [BluePointLilac/ContextMenuManager#79]
不知是否能重现问题，先po再说

[3.3.2.0] 点击`其他规则`-`增强菜单`或者`三方规则`时候会出现 unhandled exceptions

Windows 10 Enterprise 21H1 19043.1165 en-US

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ContextMenuManager.Controls.Interfaces.GroupPathItem..ctor(String targetPath, PathType pathType)
>    at ContextMenuManager.Controls.EnhanceMenusList.LoadItems()
>    at ContextMenuManager.MainForm.SwitchOtherRuleItem()
>    at BluePointLilac.Controls.MySideBar.OnMouseDown(MouseEventArgs e)
>    at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> `----------------------------------------`
> ContextMenuManager
>     Assembly Version: 3.3.2.0
>     Win32 Version: 3.3.2.0
>     CodeBase: file:///Y:/ContextMenuManager.NET.4.0.exe
> `----------------------------------------`
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> `----------------------------------------`
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> `----------------------------------------`
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> `----------------------------------------`
> PresentationFramework
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> `----------------------------------------`
> WindowsBase
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> `----------------------------------------`
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> `----------------------------------------`
> PresentationCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> `----------------------------------------`
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> `----------------------------------------`
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> `----------------------------------------`
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
>

**Comment by BluePointLilac** [comment]
你好，已更新3.3.3.0版本，可能是昨天你更新了字典文件但我的程序未发布更新导致的，请在程序的关于页面点击立即更新

**Comment by BluePointLilac** [comment]
您好，请问这个新版有这问题吗？然后感谢你提供的英语翻译，有两条有待补充。

**Comment by delgh1** [comment]
3.3.2.0在没有更新字典的时候就已经这样，更新3.3.3.0目前未见此问题
翻译的话有空会适当地修改~
