### ISSUE TITLE
添加识别其他程序禁用规则的功能

### ISSUE THREAD

**Issue by BluePointLilac** [BluePointLilac/ContextMenuManager#8]
各个程序禁用规则不同，用其他程序禁用的菜单项可能不会显示在此程序中。如果加入识别一些目前主流的右键菜单的禁用规则就会很友好，比如火绒、360、电脑管家等等

**Comment by iloooo** [comment]
感觉识不识别别的管理工具的规则都还好，我觉得这个功能其实最大的目的是恢复之前使用别的工具误删，想找回的右键菜单。
如果时间充裕，字典够大，可以在字典那里和软件的添加功能结合，可以自定义根据目录、文件或者自选格式添加这些已经被其他管理工具删掉隐藏的邮件菜单

**Comment by BluePointLilac** [comment]
此功能我决定放弃了，其他软件禁用规则五花八门，为了适配这些规则会拖累我自己程序的性能，得不偿失
