### ISSUE TITLE
禁用Win+X项后，无法再次启用

### ISSUE THREAD

**Issue by davictor233** [BluePointLilac/ContextMenuManager#87]
软件版本3.3.3.0 .Net 4.0，系统Win10 21H1 19043.1165
在软件里尝试关了几个Win+X项（Powershell、移动中心），重启资源管理器后应用成功，但尝试重新启用失败，重启资源管理器也无效。

在Win11虚拟机里尝试复现，发现在WinX文件夹里，指向System32的快捷方式（如移动中心、磁盘管理，加上Win10的Powershell和cmd）一旦用这个软件关掉就无法恢复，指向UWP界面的快捷方式（如网络连接、Win11的终端）关掉再开启可以恢复。

**Comment by BluePointLilac** [comment]
谢谢反馈，测试确实是这样，看来系统原生的项目还是有所不同，将紧急发布新版本，稍后将收到更新。

**Comment by BluePointLilac** [comment]
您好，已发布更新，之前禁用过的，需要还原默认
![QQ截图20210828145608](https://user-images.githubusercontent.com/55010935/131209481-a1848061-8e0a-4968-94c2-caefcfaf8e6a.png)

**Comment by davictor233** [comment]
多谢更新
