### ISSUE TITLE
文件或目录的右键菜单里并没有创建快捷方式(S)的修改

### ISSUE THREAD

**Issue by xueziang** [BluePointLilac/ContextMenuManager#90]
一直在用BandiZip解压文件，自动解压的快捷键是S，与右键里的创建快捷方式的快捷键冲突……
请问有什么解决办法吗？感谢！

**Comment by BluePointLilac** [comment]
创建快捷方式、剪切、删除这些都是基础命令，被系统内置了，不在注册表中不能自定义。
至于你说的解决方法倒是有，打开你的Bandizip安装目录，在langs文件夹里面找到SimpChinese.ini，
在823行，把括号中的字母换成别的就行。但是我的不是S是Z。
![2021-8-31 1-27-54](https://user-images.githubusercontent.com/55010935/131379819-71f4d731-f8ec-4499-ae46-1bba3d6eb44f.png)

**Comment by xueziang** [comment]
感谢老大！！！！无敌！
