### ISSUE TITLE
新建菜单项目无法正常添加 csv 文件

### ISSUE THREAD

**Issue by suifengpiaoyang** [BluePointLilac/ContextMenuManager#93]

**Comment by BluePointLilac** [comment]
我这边测试没问题，你能描述一下你那边的情况吗

**Comment by suifengpiaoyang** [comment]
> 我这边测试没问题，你能描述一下你那边的情况吗

新建的时候界面显示是正常的，但是此时鼠标右键并没有产生对应选项。点击上面的刷新后显示界面就恢复成最初状态。
此时用别的后缀名进行测试是正常的(只测试了两个)

**Comment by BluePointLilac** [comment]
可以加个QQ 1617859183 远程看看吗
